// Generic Open MCT provider for whatever TELEMETRY_TREE is currently loaded.
// TELEMETRY_TREE comes from telemetry-tree.js, generated by Python's buildOpenMCTjs().
function DictionaryPlugin() {
  return function install(openmct) {
    var NAMESPACE = 'midgard';
    var nodesByKey = {};
    var parentByKey = {};

    (function index(node, parentKey) {
      nodesByKey[node.key] = node;
      parentByKey[node.key] = parentKey;
      (node.children || []).forEach(function (child) { index(child, node.key); });
    })(TELEMETRY_TREE, null);

    function toDomainObject(node) {
	  var identifier = { namespace: NAMESPACE, key: node.key };
	  var location = parentByKey[node.key] ? NAMESPACE + ':' + parentByKey[node.key] : 'ROOT';

	  if (node.children) {
		return { identifier: identifier, name: node.name, type: 'folder', location: location };
	  }

	  var valueDef = Object.assign(
		{ key: 'value', name: node.name, hints: { range: 1 } },
		node.measurement || { format: 'number' }
	  );

	  return {
		identifier: identifier,
		name: node.name,
		type: 'midgard.telemetry',
		location: location,
		telemetry: {
		  values: [
		    valueDef,
		    { key: 'utc', name: 'Timestamp', format: 'utc', hints: { domain: 1 } }
		  ]
		}
	  };
	}

    openmct.objects.addProvider(NAMESPACE, {
      get: function (identifier) { return Promise.resolve(toDomainObject(nodesByKey[identifier.key])); }
    });

    openmct.composition.addProvider({
      appliesTo: function (domainObject) {
        var node = nodesByKey[domainObject.identifier.key];
        return domainObject.identifier.namespace === NAMESPACE && node && node.children;
      },
      load: function (domainObject) {
        var node = nodesByKey[domainObject.identifier.key];
        return Promise.resolve(node.children.map(function (c) { return { namespace: NAMESPACE, key: c.key }; }));
      }
    });

    openmct.types.addType('midgard.telemetry', { name: 'Telemetry Point', cssClass: 'icon-telemetry' });
    openmct.objects.addRoot({ namespace: NAMESPACE, key: TELEMETRY_TREE.key });
  };
}