// Auto-generated by buildOpenMCTjs() — do not edit by hand.
var TELEMETRY_TREE = {
    "name": "MIDGARD",
    "key": "midgard_root",
    "children": [
        {
            "name": "ASGARD V0.2",
            "key": "Valhala_I",
            "children": [
                {
                    "name": "Actuators",
                    "key": "Valhala_I.Actuators",
                    "children": [
                        {
                            "name": "Lockout",
                            "key": "Valhala_I.Actuators.lockout",
                            "children": [
                                {
                                    "name": "Abort",
                                    "key": "Valhala_I.Actuators.abort",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "left",
                                        "nameAlign": "right",
                                        "valueAlign": "center"
                                    }
                                },
                                {
                                    "name": "Main Lockout",
                                    "key": "Valhala_I.Actuators.main_lock",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                },
                                {
                                    "name": "Pyro Arm",
                                    "key": "Valhala_I.Actuators.pyro_arm",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                },
                                {
                                    "name": "Servo Arm",
                                    "key": "Valhala_I.Actuators.servo_arm",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                },
                                {
                                    "name": "Launch Arm",
                                    "key": "Valhala_I.Actuators.launch_arm",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Logging",
                            "key": "Valhala_I.Actuators.logging",
                            "children": [
                                {
                                    "name": "Logging",
                                    "key": "Valhala_I.Actuators.logging",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Selector",
                            "key": "Valhala_I.Actuators.selector",
                            "children": [
                                {
                                    "name": "Flight Phase",
                                    "key": "Valhala_I.Actuators.flight_phase",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "startup"
                                            },
                                            {
                                                "value": 1,
                                                "string": "pad"
                                            },
                                            {
                                                "value": 2,
                                                "string": "terminal"
                                            },
                                            {
                                                "value": 3,
                                                "string": "ascent"
                                            },
                                            {
                                                "value": 4,
                                                "string": "coast"
                                            },
                                            {
                                                "value": 5,
                                                "string": "descent"
                                            },
                                            {
                                                "value": 6,
                                                "string": "landed"
                                            },
                                            {
                                                "value": 7,
                                                "string": "shutdown"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Trigger",
                            "key": "Valhala_I.Actuators.trigger",
                            "children": [
                                {
                                    "name": "Blink LED",
                                    "key": "Valhala_I.Actuators.blink_led",
                                    "trigger": true
                                }
                            ]
                        },
                        {
                            "name": "Pyro",
                            "key": "Valhala_I.Actuators.pyro",
                            "children": [
                                {
                                    "name": "Drogue Pyro",
                                    "key": "Valhala_I.Actuators.pyro_drogue",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                },
                                {
                                    "name": "Main Pyro",
                                    "key": "Valhala_I.Actuators.pyro_main",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                },
                                {
                                    "name": "Motor Pyro",
                                    "key": "Valhala_I.Actuators.pyro_motor",
                                    "measurement": {
                                        "format": "enum",
                                        "enumerations": [
                                            {
                                                "value": 0,
                                                "string": "False"
                                            },
                                            {
                                                "value": 1,
                                                "string": "True"
                                            }
                                        ]
                                    },
                                    "switch_display": {
                                        "namePosition": "top",
                                        "nameAlign": "center",
                                        "valueAlign": "center"
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "Data_Streams",
                    "key": "Valhala_I.Data_Streams",
                    "children": [
                        {
                            "name": "Position",
                            "key": "Valhala_I.Data_Streams.position",
                            "children": [
                                {
                                    "name": "Position X",
                                    "key": "Valhala_I.Data_Streams.pos_x",
                                    "measurement": {
                                        "units": "m",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Position Y",
                                    "key": "Valhala_I.Data_Streams.pos_y",
                                    "measurement": {
                                        "units": "m",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Position Z",
                                    "key": "Valhala_I.Data_Streams.pos_z",
                                    "measurement": {
                                        "units": "m",
                                        "format": "number"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Velocity",
                            "key": "Valhala_I.Data_Streams.velocity",
                            "children": [
                                {
                                    "name": "Velocity X",
                                    "key": "Valhala_I.Data_Streams.vel_x",
                                    "measurement": {
                                        "units": "m/s",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Velocity Y",
                                    "key": "Valhala_I.Data_Streams.vel_y",
                                    "measurement": {
                                        "units": "m/s",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Velocity Z",
                                    "key": "Valhala_I.Data_Streams.vel_z",
                                    "measurement": {
                                        "units": "m/s",
                                        "format": "number"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Acceleration",
                            "key": "Valhala_I.Data_Streams.acceleration",
                            "children": [
                                {
                                    "name": "Acceleration X",
                                    "key": "Valhala_I.Data_Streams.accel_x",
                                    "measurement": {
                                        "units": "m/s^2",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Acceleration Y",
                                    "key": "Valhala_I.Data_Streams.accel_y",
                                    "measurement": {
                                        "units": "m/s^2",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Acceleration Z",
                                    "key": "Valhala_I.Data_Streams.accel_z",
                                    "measurement": {
                                        "units": "m/s^2",
                                        "format": "number"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Attitude",
                            "key": "Valhala_I.Data_Streams.attitude",
                            "children": [
                                {
                                    "name": "Pitch",
                                    "key": "Valhala_I.Data_Streams.pitch",
                                    "measurement": {
                                        "units": "deg",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Roll",
                                    "key": "Valhala_I.Data_Streams.roll",
                                    "measurement": {
                                        "units": "deg",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "Yaw",
                                    "key": "Valhala_I.Data_Streams.yaw",
                                    "measurement": {
                                        "units": "deg",
                                        "format": "number"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Compass",
                            "key": "Valhala_I.Data_Streams.compass",
                            "children": [
                                {
                                    "name": "Heading",
                                    "key": "Valhala_I.Data_Streams.heading",
                                    "measurement": {
                                        "units": "deg",
                                        "format": "number"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "Pressure",
                            "key": "Valhala_I.Data_Streams.pressure",
                            "children": [
                                {
                                    "name": "Static Pressure",
                                    "key": "Valhala_I.Data_Streams.static_pressure",
                                    "measurement": {
                                        "units": "Pa",
                                        "format": "number"
                                    }
                                }
                            ]
                        },
                        {
                            "name": "GPS",
                            "key": "Valhala_I.Data_Streams.gps",
                            "children": [
                                {
                                    "name": "GPS Latitude",
                                    "key": "Valhala_I.Data_Streams.gps_lat",
                                    "measurement": {
                                        "units": "deg",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "GPS Longitude",
                                    "key": "Valhala_I.Data_Streams.gps_lon",
                                    "measurement": {
                                        "units": "deg",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "GPS Altitude",
                                    "key": "Valhala_I.Data_Streams.gps_alt",
                                    "measurement": {
                                        "units": "m",
                                        "format": "number"
                                    }
                                },
                                {
                                    "name": "GPS Time",
                                    "key": "Valhala_I.Data_Streams.gps_time",
                                    "measurement": {
                                        "units": "unix_s",
                                        "format": "number"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
};
