[meta]
name = "Rocket"
description = "Generic Rocket"
type = "rocket"
first_phase = "startup"

[meta.switch_display]
namePosition = "top"
nameAlign = "center"
valueAlign = "center"

# ── Lockouts ───────────────────────────────────────────────────────────
[[actuator]]
id = "abort"
name = "Abort"
description = "Emergency shutdown"
type = "abort"
sync_group = "abort"
default = false

[actuator.switch_display]
namePosition = "left"
nameAlign = "right"

[[actuator]]
id = "main_lock"
name = "Main Lockout"
description = "Disarms all other lockouts and actuators"
type = "lockout"
sync_group = "main_lock"
default = false
armed_by = [] # all must be true
disarmed_by = ["lockout.abort"] # all must be false

# ── Logging ────────────────────────────────────────────────────────────
[[actuator]]
id = "logging"
name = "Logging"
description = "Log commands and data to csv file"
type = "switch"
sync_group = "logging"
default = false

# ── Terminal ───────────────────────────────────────────────────────────
#[[actuator]]
#id = "terminal_log"
#name = "Terminal"
#description = "Displays the python terminal in OpenMCT"
#type = "message"

# ── Phases ─────────────────────────────────────────────────────────────
[[actuator]]
id = "flight_phase"
name = "Flight Phase"
description = "Phase of flight selector/display"
type = "selector"
#function_file = "test_thread"
#function = "run"
#function_type = "thread"
default = "startup"
nominal = "pad"

[[state]]
id = "startup"
name = "Startup"
description = "Vehicle is powering on"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.pad"]
sources = ["auto", "peripheral"]

[[state]]
id = "pad"
name = "Pad"
description = "Vehicle on pad, awaiting terminal"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.terminal"]
sources = ["auto", "user", "peripheral"]

[[state]]
id = "terminal"
name = "Terminal"
description = "Vehicle in countdown, awaiting launch"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.ascent", "phase.pad"]
armed_by = ["lockout.main_lock"] # all must be true
disarmed_by = ["lockout.abort"] # all must be false
sources = ["user"]
#do_function = true

[[state]]
id = "ascent"
name = "Ascent"
description = "Vehicle has begun burn"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.coast"]
sources = ["peripheral"]

[[state]]
id = "coast"
name = "Coast"
description = "Vehicle is no longer under thrust"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.descent"]
sources = ["peripheral"]

[[state]]
id = "descent"
name = "Descent"
description = "Vehicle has reach apogee and is now descending"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.landed"]
sources = ["peripheral"]

[[state]]
id = "landed"
name = "Landed"
description = "Vehicle has touched down"
type = "phase"
parent = "flight_phase"
transition_to = ["phase.shutdown"]
sources = ["peripheral"]

[[state]]
id = "shutdown"
name = "Shutdown"
description = "Vehicle is powering down"
type = "phase"
parent = "flight_phase"
transition_to = []
sources = ["auto", "user", "peripheral"]