[meta]
name = "Rocket"
description = "Generic Rocket"
type = "rocket"
first_phase = "startup"

# ── Lockouts ───────────────────────────────────────────────────────────
[[lockout]]
id = "abort"
name = "Abort"
description = "Emergency shutdown"
default = false

[[lockout]]
id = "main_lock"
name = "Main Lockout"
description = "Disarms all other lockouts and actuators"
default = false
armed_by = [] # all must be true
disarmed_by = ["lockout.abort"] # all must be false

# ── Status ─────────────────────────────────────────────────────────────
[[phase]]
id = "startup"
name = "Startup"
description = "Vehicle is powering on"
transition_to = ["phase.pad"]
set_by = ["auto"]

[[phase]]
id = "pad"
name = "Pad"
description = "Vehicle on pad, awaiting terminal"
transition_to = ["phase.terminal"]
set_by = ["auto", "user"]

[[phase]]
id = "terminal"
name = "Terminal"
description = "Vehicle in countdown, awaiting launch"
transition_to = ["phase.ascent", "phase.pad"]
set_by = ["user"]

[[phase]]
id = "ascent"
name = "Ascent"
description = "Vehicle has begun burn"
transition_to = ["phase.coast"]
set_by = ["peripheral"]

[[phase]]
id = "coast"
name = "Coast"
description = "Vehicle is no longer under thrust"
transition_to = ["phase.descent"]
set_by = ["peripheral"]

[[phase]]
id = "descent"
name = "Descent"
description = "Vehicle has reach apogee and is now descending"
transition_to = ["phase.landed"]
set_by = ["peripheral"]

[[phase]]
id = "landed"
name = "Landed"
description = "Vehicle has touched down"
transition_to = ["phase.shutdown"]
set_by = ["peripheral"]

[[phase]]
id = "shutdown"
name = "Shutdown"
description = "Vehicle is powering down"
transition_to = []
set_by = ["auto", "user", "peripheral"]
